server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  application:
    name: kurung_backend

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true

  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: c##kurung
    password: kurung2025
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: kurunghelpdesk@gmail.com
    password: ilko lpxn eyti fmkh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /api/v1/kurung/**

jwt:
  secret: vrDt6Hhffv9gPPEEHDBVhxY4W+gf//bxDgVljRr/+8z1ZxqEdgTmDDZ/UIquJuWQdZmJ8mz/DuzLF/pmcMFaqw==
  access_expiration: 1800000
  refresh_expiration: 84600000
