server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  application:
    name: kurung_backend

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true

  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: c##kurung
    password: kurung2025
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: kurunghelpdesk@gmail.com
    password: ilko lpxn eyti fmkh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 10000
          connectiontimeout: 10000
          writetimeout: 10000

springdoc:
  swagger-ui:
    path: /api-test  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
  paths-to-match:
    - /api/v1/kurung/** # swagger-ui에 표시할 api의 엔드포인트 패턴

jwt:
  secret: vrDt6Hhffv9gPPEEHDBVhxY4W+gf//bxDgVljRr/+8z1ZxqEdgTmDDZ/UIquJuWQdZmJ8mz/DuzLF/pmcMFaqw==
  access_expiration: 1800000
  refresh_expiration: 84600000

# 소셜 로그인 API 설정
social:
  kakao:
    api-url: https://kapi.kakao.com
    client-id: ${KAKAO_CLIENT_ID:e0ccd9a1366d275242dc304128c7ef03}
    client-secret: ${KAKAO_CLIENT_SECRET:58969640d74f895c291eee6cb53cfa89}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:3000/auth/kakao/callback}
  naver:
    api-url: https://openapi.naver.com
    client-id: ${NAVER_CLIENT_ID:your_naver_client_id}
    client-secret: ${NAVER_CLIENT_SECRET:your_naver_client_secret}
    redirect-uri: ${NAVER_REDIRECT_URI:http://localhost:3000/auth/naver/callback}
